#!/bin/bash
N=~/2024Q4_grotte/LE_PAUL241116_2_0_1_QGIS.pdf
$(dirname $0)/sealgood inject $N
pdftotext /tmp/$(basename $N) - |
#tee /dev/stderr|
awk '/awk/{next}
/BEGIN SEALGOOD BASE64/ {
  sub(".*BEGIN SEALGOOD BASE64:","")
  printf("%s", "### BEGIN SEALGOOD ")
  system("base64 -d <<END"ORS $1 ORS "END")
  exit
}'
