#!/bin/bash
export mydir="$(cd "$(dirname "$0")";pwd)" myname="$(basename "$0")"
(cd "$mydir/../../docs" && make ../tests/integration/$myname.stdout)
exec 1> >(tee $mydir/$myname.stdout)

. "$mydir/test_prereq"

####################################################################
# lookup/PEM pubkey                                                #
# date/PEM pubkey                                                  #
# get_payload                                                      #
# locale/{{run,data}/fr,{run,data}/es,{run,data}/pt,{run,data}/us} #
####################################################################
parallel "mydif $LINENO ../samples/test_date_{} < <(
LANGUAGE={} sealgood date < $mydir/../samples/pempub 2>/dev/null | tee $TMPDIR/test_date_{}_tee | sed -e 's/\(^MIIV\).*/\1/' )
" ::: us es fr pt

###################################
# lookup/file_or_url_list         #
# lookup/sealgood+PEM pubkey      #
# lookup/gzip                     #
# date/sealgood+PEM pubkey        #
# clean/sealgood+PEM pubkey       #
# verify/sealgood+PEM pubkey      #
# locale/{run/es,data/{fr,es,us}} #
###################################
mydif $LINENO ../samples/test_date_pubkey  < <(( ls $mydir/../samples/test_date_{es,fr,pt} |
LANGUAGE=es sealgood date verify |
                      tee $TMPDIR/pubkeys.tgz | # garde pour le test suivant
                      zcat|strings -n12 -weS) 2>&1 | sed -e 's/\(^MIIV\).*/\1/' -e 's/\(^Time stamp:\).*/\1/' )

############################
# lookup/tar+gzip          #
# date/sealgood+tar+gzip #
# lookup/sealgood+tar+gzip #
# verify/sealgood+tar+gzip #
# locale/{run,data}/us     #
############################
mydif $LINENO ../samples/test_date_gzip  < <(( cat $TMPDIR/pubkeys.tgz |
LANGUAGE=us sealgood date verify |
                      zcat|strings -n12 -weS) 2>&1 | sed -e 's/\(^MIIV\).*/\1/' -e 's/\(^Time stamp:\).*/\1/' \
                      -e 's/\(^wc       :\)   .[^ ].*/\1/' )

####################################################################
# lookup/PEM pubkey                                                #
# date/PEM pubkey                                                  #
# get_payload                                                      #
# locale/{{run,data}/fr,{run,data}/es,{run,data}/pt,{run,data}/us} #
####################################################################
parallel "mydif $LINENO ../samples/test_date_{} < <((
LANGUAGE={} sealgood clean date < $mydir/../samples/test_date_pt 2>/dev/null) 2>&1 | sed -e 's/\(^MIIV\).*/\1/' )
" ::: us es fr pt

##############
# lookup/pdf #
# date/pdf   #
# verify/pdf #
##############
mydif $LINENO ../samples/test_date_pdf < <( cat $mydir/../samples/svg.pdf |
(LANGUAGE=fr sealgood date verify | tee /tmp/svg.date.pdf) 2>&1 | sed -e 's/\(Time stamp:\).*/\1/' -e 's/\(^MIIV\).*/\1/' )

##############
# date/pdf   #
# verify/pdf #
##############
mydif $LINENO ../samples/test_date_tgz_pdf < <( while ((++i < 4));do cp -l /tmp/svg.date{,_$i}.pdf && echo /tmp/svg.date_$i.pdf;done |
(LANGUAGE=fr sealgood date verify  | zcat) 2>&1 | strings -weS -n12 | sed -e 's/\(Time stamp:\).*/\1/' -e 's/\(^MIIV\).*/\1/' )

##############
# clean/pdf  #
# date/pdf   #
# verify/pdf #
##############
mydif $LINENO ../samples/test_date_es_tgz_pdf < <( while ((++i < 4));do cp -l /tmp/svg.date{,_$i}.pdf && echo /tmp/svg.date_$i.pdf;done |
(LANGUAGE=es sealgood clean date verify | zcat) 2>&1 | strings -weS -n12 | sed -e 's/\(Time stamp:\).*/\1/' -e 's/\(^MIIV\).*/\1/' )

####################################################################
# lookup/PEM pubkey                                                #
# date/PEM pubkey                                                  #
# get_payload                                                      #
# locale/{{run,data}/fr,{run,data}/es,{run,data}/pt,{run,data}/us} #
####################################################################
parallel "mydif $LINENO ../samples/test_verify_{1}_{2} < <(
LANGUAGE={1} sealgood verify < $TMPDIR/test_date_{2}_tee 2>&1 | sed -e 's/\(^MIIV\).*/\1/'  -e 's/\(^Time stamp:\).*/\1/' )
" ::: us es fr pt ::: us es fr pt
