#!/bin/bash
export mydir="$(cd "$(dirname "$0")";pwd)" myname="$(basename "$0")"
(cd "$mydir/../../docs" && make ../tests/integration/$myname.stdout)
exec 1> >(tee $mydir/$myname.stdout)

. "$mydir/test_prereq"

########################################################################
# help                                                                 #
# locale/{{run/fr,data/},{run/es,data/},{run/us,data/},{run/pt,data/}} #
########################################################################
parallel "mydif $LINENO ../../docs/{}/help_{}.md < <(LANGUAGE={} sealgood help 2>&1 | mdstyle console)" ::: us es fr pt

#############
# clean/pdf #
#############
mydif $LINENO ../samples/svg.pdf < <( cat /tmp/svg.date.pdf |
LANGUAGE=fr sealgood clean 2>/dev/null )

#################################################################################################
# lookup/PEM pubkey                                                                             #
# clean/PEM pubkey                                                                              #
# locale/run/{fr\ locale/data/{fr,es,us},es\ locale/data/{fr,es,us},us\ locale/data/{fr,es,us}} #
#################################################################################################
parallel "mydif $LINENO ../samples/test_clean < <(
LANGUAGE={1} sealgood clean < $mydir/../samples/test_date_{2} 2>/dev/null)" ::: fr es us pt ::: fr es us pt

#################################################################################################
# lookup/file_or_url_list                                                                       #
# lookup/sealgood+PEM pubkey                                                                    #
# clean/PEM pubkey                                                                              #
# locale/run/{fr\ locale/data/{fr,es,us},es\ locale/data/{fr,es,us},us\ locale/data/{fr,es,us}} #
#################################################################################################
parallel --linebuffer "mydif $LINENO ../samples/test_clean_list_{} < <(( ls $mydir/../samples/test_date_{fr,es,us,pt} |
LANGUAGE={} sealgood clean | tar -zvxOf-) 2>&1)" ::: fr es us pt

###################################
# lookup/file_or_url_list         #
# $STOPFILE                       #
# locale/{run,data}/fr            #
###################################
parallel "mydif $LINENO ../samples/test_stopfile_{}  < <(ls $mydir/../samples/test_date_{fr,es,us,pt} |
LANGUAGE=fr STOPFILE=/stopfile sealgood {} 2>&1)" ::: clean date
