#!/bin/bash
export mydir="$(cd "$(dirname "$0")";pwd)" myname="$(basename "$0")"
(cd "$mydir/../../docs" && make ../tests/integration/$myname.stdout)
exec 1> >(tee $mydir/$myname.stdout)

. "$mydir/test_prereq"

########################################################################
# help                                                                 #
# locale/{{run/fr,data/},{run/es,data/},{run/us,data/},{run/pt,data/}} #
########################################################################
parallel "mydif $LINENO ../../docs/{}/help_{}.md < <(LANGUAGE={} sealgood help 2>&1 | mdstyle console)" ::: us es fr pt

####################################################################
# lookup/PEM pubkey                                                #
# date/PEM pubkey                                                  #
# get_payload                                                      #
# locale/{{run,data}/fr,{run,data}/es,{run,data}/pt,{run,data}/us} #
####################################################################
parallel "mydif $LINENO ../samples/test_date_{} < <((
LANGUAGE={} sealgood date < $mydir/../samples/pempub 2>/dev/null) 2>&1 | sed -e 's/\(^MIIV\).*/\1/' )
" ::: us es fr pt

#################################################################################################
# lookup/PEM pubkey                                                                             #
# clean/PEM pubkey                                                                              #
# locale/run/{fr\ locale/data/{fr,es,us},es\ locale/data/{fr,es,us},us\ locale/data/{fr,es,us}} #
#################################################################################################
parallel "mydif $LINENO ../samples/test_clean < <(
LANGUAGE={1} sealgood clean < $mydir/../samples/test_date_{2} 2>/dev/null)" ::: fr es us pt ::: fr es us pt

#################################################################################################
# lookup/file_or_url_list                                                                       #
# lookup/sealgood+PEM pubkey                                                                    #
# clean/PEM pubkey                                                                              #
# locale/run/{fr\ locale/data/{fr,es,us},es\ locale/data/{fr,es,us},us\ locale/data/{fr,es,us}} #
#################################################################################################
parallel --linebuffer "mydif $LINENO ../samples/test_clean_list_{} < <(( ls $mydir/../samples/test_date_{fr,es,us,pt} |
LANGUAGE={} sealgood clean | tar -zvxOf-) 2>&1)" ::: fr es us pt

###################################
# lookup/file_or_url_list         #
# lookup/sealgood+PEM pubkey      #
# lookup/gzip                     #
# date/sealgood+PEM pubkey        #
# clean/sealgood+PEM pubkey       #
# verify/sealgood+PEM pubkey      #
# locale/{run/es,data/{fr,es,us}} #
###################################
mydif $LINENO ../samples/test_date_pubkey  < <(( ls $mydir/../samples/test_date_{es,fr,pt} |
LANGUAGE=es sealgood date verify |
                      tee $TMPDIR/pubkeys.tgz | # garde pour le test suivant
                      zcat|strings -n12 -weS) 2>&1 | sed -e 's/\(^MIIV\).*/\1/' -e 's/\(^Time stamp:\).*/\1/' )

############################
# lookup/tar+gzip          #
# date/sealgood+tar+gzip #
# lookup/sealgood+tar+gzip #
# verify/sealgood+tar+gzip #
# locale/{run,data}/us     #
############################
mydif $LINENO ../samples/test_date_gzip  < <(( cat $TMPDIR/pubkeys.tgz |
LANGUAGE=us sealgood date verify |
                      zcat|strings -n12 -weS) 2>&1 | sed -e 's/\(^MIIV\).*/\1/' -e 's/\(^Time stamp:\).*/\1/' \
                      -e 's/\(^wc       :\)   .[^ ].*/\1/' )

###################################
# lookup/file_or_url_list         #
# $STOPFILE                       #
# locale/{run,data}/fr            #
###################################
parallel "mydif $LINENO ../samples/test_stopfile_{}  < <(ls $mydir/../samples/test_date_{fr,es,us,pt} |
LANGUAGE=fr STOPFILE=/stopfile sealgood {} 2>&1)" ::: clean date
