#!/bin/bash
mydir="$(cd "$(dirname "$0")" && pwd)"
source "$mydir"/../../bin/filetypes
source "$mydir"/../../bin/sealgood
tmpdir=$(mktemp -d)
cd $tmpdir

# lookup extract gzip
[[ "$(lookup inject < "$mydir"/../samples/pubkeys.tgz)" == "application/tar+gzip; charset=binary" ]] || echo KO $LINENO >&2

  diff -q lookup.inject{,.original}                            || echo KO $LINENO >&2
  diff -q lookup.inject.unzip      <(zcat lookup.inject)       || echo KO $LINENO >&2
  diff -q lookup.inject        "$mydir"/../samples/pubkeys.tgz || echo KO $LINENO >&2
  chmod -w lookup.inject{,.original,.unzip}

  [ -s lookup.inject.payload ]                                 && echo KO $LINENO >&2
>lookup.inject.payload get_payload <lookup.inject.unzip
  [ -s lookup.inject.payload ]                                 || echo KO $LINENO >&2

>lookup.test2 inject_type  "application/tar+gzip; charset=binary"
  [[ "$(file -bi  lookup.test2)" == "application/gzip; charset=binary" ]] || echo KO $LINENO >&2
extract_gzip     test2      "application/gzip; charset=binary"
  [ -s lookup.test2.payload ]                                  || echo KO $LINENO >&2

  diff -q lookup.{test2,inject}.original                       || echo KO $LINENO >&2
  diff -q lookup.{test2,inject}.unzip                          || echo KO $LINENO >&2

[[ "$(lookup <lookup.test2)" == "application/sealgood+tar+gzip; charset=binary" ]] || echo KO $LINENO >&2

ls $PWD/*
